# backend-deployment-20i-0958.yaml (with additional features)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-20i-0958
  labels:
    app: backend-20i-0958
    roll-number: 20i-0958
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-20i-0958
  template:
    metadata:
      labels:
        app: backend-20i-0958
        roll-number: 20i-0958
    spec:
      containers:
      - name: backend
        image: shersher/scdfinalexam/backend:20i-0958
        ports:
        - containerPort: 0958
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 0958
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 0958
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-20i-0958
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend-20i-0958
  ports:
    - protocol: TCP
      port: 80
      targetPort: 0958
  type: LoadBalancer
