# frontend-deployment-20i-0958.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-20i-0958
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-20i-0958
  template:
    metadata:
      labels:
        app: frontend-20i-0958
    spec:
      containers:
      - name: frontend
        image: shersher/scdfinalexam:frontend-20i-0958
        ports:
        - containerPort: 958
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-20i-0958
spec:
  selector:
    app: frontend-20i-0958
  ports:
    - protocol: TCP
      port: 80
      targetPort: 958
  type: LoadBalancer
